# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

homeassistant:
  # Name of the location where Home Assistant is running
  name: Smultronstaelle
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 140
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

# API
api:

# mobile app
mobile_app:

# iOS support
ios:

# health check
system_health:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# Enables Sun
sun:

# View all events in a logbook
# logbook:

# Enables a map showing the location of tracked devices
# map:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
automation old: !include static_automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml

maxcube:
  gateways:
    - host: 192.168.20.48

lovelace:
  mode: yaml

shell_command:
  update_from_git: 'cd /root/config; /usr/bin/git pull'
