- alias: Anwesenheitsbeleuchtung einschalten
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
    - entity_id: switch.steckdose_1
      service: switch.turn_on

- alias: Anwesenheitsbeleuchtung ausschalten
  description: ''
  trigger:
  - at: 01:00
    platform: time
  condition: []
  action:
    - entity_id: switch.steckdose_1
      service: switch.turn_off

- alias: Bewässerung Balkon
  description: ''
  trigger:
  - hours: /1
    minutes: '5'
    platform: time_pattern
  condition:
  - condition: or
    conditions:
    - after: 07:00:00
      before: 09:00:00
      condition: time
    - after: '19:00:00'
      before: '21:00:00'
      condition: time
  action:
  - data: {}
    entity_id: script.bewaesserung
    service: script.turn_on

- alias: Weihnachtsbeleuchtung einschalten
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - entity_id: group.christmas
    service: switch.turn_on

- alias: Weihnachtsbeleuchtung ausschalten
  description: ''
  trigger:
  - at: 01:00:00
    platform: time
  condition: []
  action:
  - entity_id: group.christmas
    service: switch.turn_off

- alias: "MQTT discovery for all devices"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "sonoffs/cmnd/SetOption19"
        payload: "1"

- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "sonoffs/cmnd/state"
        payload: ""

- alias: Update from Repository
  description: ''
  trigger:
    platform: webhook
    webhook_id: update
  action:
    - service: shell_command.update_from_git
    - service: homeassistant.reload_core_config
    - service: script.reload
    - service: lovelace.reload_resources
    - service: automation.reload
    - service: group.reload
