- alias: Anwesenheitsbeleuchtung einschalten
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
    - entity_id: switch.steckdose_1
      service: switch.turn_on

- alias: Anwesenheitsbeleuchtung ausschalten
  description: ''
  trigger:
  - at: 01:00
    platform: time
  condition: []
  action:
    - entity_id: switch.steckdose_1
      service: switch.turn_off

- alias: Bewässerung Balkon
  description: ''
  trigger:
  - hours: '8'
    minutes: '5'
    platform: time_pattern
  - hours: '13'
    minutes: '5'
    platform: time_pattern
  - hours: '18'
    minutes: '5'
    platform: time_pattern
  action:
  - data: {}
    entity_id: script.bewaesserung
    service: script.turn_on

- alias: Weihnachtsbeleuchtung einschalten
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - entity_id: group.christmas
    service: switch.turn_on

- alias: Weihnachtsbeleuchtung ausschalten
  description: ''
  trigger:
  - at: 01:00:00
    platform: time
  condition: []
  action:
  - entity_id: group.christmas
    service: switch.turn_off

- alias: Washingmachine is idle
  description: ''
  trigger:
    - platform: numeric_state
      entity_id: sensor.waschmaschine_energy_current
      above: 0.02
      below: 0.1
      for: '00:02:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_washingmachine
        option: 'Idle'

- alias: Washingmachine is running
  description: ''
  trigger:
    - platform: numeric_state
      entity_id: sensor.waschmaschine_energy_current
      above: 0.5
      for: '00:02:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_washingmachine
        option: 'Running'

- alias: Washingmachine is off
  description: ''
  trigger:
    - platform: numeric_state
      entity_id: sensor.waschmaschine_energy_current
      below: 0.01
      for: '00:02:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_washingmachine
        option: 'Off'
            
- alias: "MQTT discovery for all devices"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "sonoffs/cmnd/SetOption19"
        payload: "1"

- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "sonoffs/cmnd/state"
        payload: ""

- alias: Update from Repository
  description: ''
  trigger:
    platform: webhook
    webhook_id: update
  action:
    - service: shell_command.update_from_git
    - service: homeassistant.reload_core_config
    - service: script.reload
    - service: lovelace.reload_resources
    - service: automation.reload
    - service: group.reload
