title: Smultronstaelle

views:
  - title: Home
    icon: mdi:home
    path: default_view
    cards:
      - type: entity-button
        tap_action:
          action: toggle
        hold_action:
          action: none
        show_icon: true
        show_name: true
        entity: switch.steckdose_1
        icon: 'mdi:lamp'
        icon_height: 64px
      - type: entity-button
        tap_action:
          action: toggle
        hold_action:
          action: none
        show_icon: true
        show_name: true
        entity: switch.steckdose_2
        icon: 'mdi:floor-lamp'
        icon_height: 64px
  - title: Heizung
    icon: mdi:fire
    path: heizung
    cards:
      - name: Wohnen Nord
        entity: climate.wohnzimmer_thermostat_nord
        type: thermostat
      - name: Wohnen Ost
        entity: climate.wohnzimmer_thermostat_ost
        type: thermostat
      - name: Wohnen Süd
        entity: climate.wohnzimmer_thermostat_sud
        type: thermostat
      - name: Heiko
        entity: climate.heiko_thermostat
        type: thermostat
      - name: Tom
        entity: climate.tom_thermostat
        type: thermostat
      - name: Schlafzimmer
        entity: climate.schlafzimmer_thermostat_1
        type: thermostat
      - name: großes Bad
        entity: climate.grosses_bad_thermostat
        type: thermostat
      - name: kleines Bad
        entity: climate.kleines_bad_thermostat
        type: thermostat
  - title: Weihnachtsbeleuchtung
    icon: mdi:pine-tree
    path: christmas
    cards:
      - type: entity-button
        entity: group.christmas
        show_icon: true
        show_name: true
        tap_action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: group.christmas
  - title: Automatisierungen
    icon: mdi:settings-outline
    path: automation
    cards:
      - title: Beleuchtung
        show_header_toggle: true
        type: entities
        entities: 
          - entity: automation.anwesenheitsbeleuchtung_einschalten
          - entity: automation.anwesenheitsbeleuchtung_ausschalten
      - title: Bewässerung
        show_header_toggle: true
        type: entities
        entities: 
          - entity: automation.bewasserung_balkon_starten
      - title: Weihnachtsbeleuchtung
        show_header_toggle: true
        type: entities
        entities: 
          - entity: automation.weihnachtsbeleuchtung_einschalten
          - entity: automation.weihnachtsbeleuchtung_ausschalten
