homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 140
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

# mobile app
mobile_app:

# health check
system_health:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

# Load UI config from yaml
lovelace:
  mode: yaml

# Sensors
sensor:
  # Weather prediction
  - platform: yr
    name: Wetter
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - cloudiness
  # Temerature from Thermostat
  - platform: template
    sensors:
      livingroom_current_temperature:
        friendly_name: Temperatur Wohnzimmer
        value_template: "{{ state_attr('climate.wohnzimmer_thermostat_ost', 'current_temperature') }}"
        unit_of_measurement: "°C"
      sleepingroom_current_temperature:
        friendly_name: Temperatur Schlafzimmer
        value_template: "{{ state_attr('climate.schlafzimmer_thermostat_1', 'current_temperature') }}"
        unit_of_measurement: "°C"
      heiko_current_temperature:
        friendly_name: Temperatur Heikos Zimmer
        value_template: "{{ state_attr('climate.heiko_thermostat', 'current_temperature') }}"
        unit_of_measurement: "°C"
      tom_current_temperature:
        friendly_name: Temperatur Toms Zimmer
        value_template: "{{ state_attr('climate.tom_thermostat', 'current_temperature') }}"
        unit_of_measurement: "°C"
      small_bath_current_temperature:
        friendly_name: Temperatur kleines Bad
        value_template: "{{ state_attr('climate.kleines_bad_thermostat', 'current_temperature') }}"
        unit_of_measurement: "°C"
      grand_bath_current_temperature:
        friendly_name: Temperatur großes Bad
        value_template: "{{ state_attr('climate.grosses_bad_thermostat', 'current_temperature') }}"
        unit_of_measurement: "°C"
      internet_rtt:
        friendly_name: Internet RTT (Cloudflare)
        value_template: "{{ state_attr('states.binary_sensor.internet', 'round_trip_time_avg') }}"
        unit_of_measurement: ms

# Binary sensors
binary_sensor:
  - platform: ping
    host: 1.1.1.1
    count: 2
    scan_interval:
      seconds: 60
    name: Internet

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

# MQTT
mqtt:
  password: !secret mqtt_password
  discovery: true

# Max! Cube
maxcube:
  gateways:
    - host: 192.168.10.20
      port: 62910

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include_dir_list scenes
